### ISSUE TITLE
These keywords are being captured with all the spaces in front. Is this a correct behavior?

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#42]
We made some workarounds for this issue already, but it would be nice to make it work correctly from your side.

METHOD:
![image](https://github.com/user-attachments/assets/24743ab8-8d19-40a3-8cb2-c73bf4500c03)

END (CLASS):
![image](https://github.com/user-attachments/assets/66be3eb4-83db-4d90-89f0-ace0309df8a2)

DEFINE (PROPERTY):
![image](https://github.com/user-attachments/assets/b696496d-6381-4931-88c0-f3261721e042)

comments:
![image](https://github.com/user-attachments/assets/09ba74bc-01e6-4ee3-b39a-b90e74693578)

**Comment by jkbz64** [comment]
I guess what you don't like is that is says method definition starts at 0 line, this is due to whitespace handling decision done in the parser - specificially this line ` extras: ($) => [$.comment, $.include, /[\s\f\uFEFF\u2060\u200B]|\\\r?\n/],`, it says that each of the element (third is whitespace regex) can appear everywhere in the syntax BEFORE the element, so in this case when it tries to match kw("METHOD") it also matches whitespace BEFORE it (whitespace does not appear in the syntax tree due to it not having a name like comment/include), not having whitespace rule in the extras would require manual whitespace handling which would be extremely complicated in progress case as it does not care about whitespace at all. I could maybe pull off some workaround for your case in CLASS'es but no idea how would I go about doing a global fix (except for removing whitespace from extras, which.... will break the entire parser and require code redesign for the entire parser)

![image](https://github.com/user-attachments/assets/1a6cc202-0115-4192-9a77-de6fda69b5b2)

**Comment by PauliusKu** [comment]
Thanks for the explanation.
Okay, I think we can manage this issue on our side then.
I am closing this ticket.
