### ISSUE TITLE
Short definition of property has an error

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#52]
![image](https://github.com/user-attachments/assets/7ec1d082-3881-4a9f-9c0a-30cd053f0015)

Reference: https://docs.progress.com/bundle/abl-reference/page/VAR-statement.html

**Comment by jkbz64** [comment]
I wouldn't really consider it shorthand as it can define multiple variables and assign values which define can't do (only initial static constants), also don't know if the VAR statement variables are hoisted up like DEFINE is because I don't have an access to 12.x setup. I've decided to name it var_statement and not group it with define_variable, not sure if that's the right way...

**Comment by PauliusKu** [comment]
Thanks, I think it's better to have it separately
