### ISSUE TITLE
GET and SET in Property definition throws Error when containing Additional Logic

### ISSUE THREAD

**Issue by eglekaz** [usagi-coffee/tree-sitter-abl#56]
Example:
```
class TestClass:

    define public property m_Total as integer no-undo
        get.
        set.
  
    define public property Totals as integer no-undo
        get:
            if m_Total < 0 then
                return 0.
            else
                return m_Total.
            end.
        end get.
          
        set (newValue as integer):
            m_Total = newValue.
        end set.  
end class.
```

**Comment by jkbz64** [comment]
Few things:
- Getter did not have body variant, fixed that.
- Your if else inside getter is invalid code, AFAIK you can't use 'end.' for else when using if else with (single) terminated statement, only when doing THEN DO: variant.
- Setter broke because of name of the second variable, it contains NEW at the beginning and new keyword has priority over variable name so it tried to parse new expression :( This is related to the same issue at #53
